output: ControlWork.o
	g++ ControlWork.o -o output

install: ControlWork.cpp
	g++ ControlWork.cpp
	cp output /Users/yaslomg/ControlWork/bin

uninstall: ControlWork.cpp
	rm /Users/yaslomg/ControlWork/ControlWork.o
	rm /Users/yaslomg/ControlWork/bin/output
clean: 
	rm *.o output